version: 1.2
workflows:
- name: 'RSEM_build_reference'
  subclass: WDL
  publish: true
  primaryDescriptorPath: /rsem_build_ref.wdl
  testParameterFiles:
  - /rsem_build_ref.json
  authors:
  - name: Nicola
